spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:54924;databaseName=TaskDB;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
